version: '3.2'
services:
  mongo:
    image: mongo
    restart: always
    expose:
    - "27017"

  backend:
    image: static_site_backend
    build:
      context: static-site-backend
      dockerfile: Dockerfile-dev
      args:
        JAR_FILE: out/static-site-backend.jar
    restart: always
    ports:
    - "8080:8080"
    environment:
    - SPRING_PROFILES_ACTIVE=dev

  frontend:
    image: static_site_frontend
    build:
      context: static-site-frontend
      dockerfile: Dockerfile-dev
      args:
        JAR_FILE: out/static-site-frontend.jar
    restart: always
    ports:
    - "80:8080"
